name: devops-intern-test_feature_branch

on:
  push:
    branches-ignore:
      - master

jobs:
  feature-brand-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
        working-directory: src/
      - name: NPM Build
        run: npm run build --if-present
        working-directory: src/
      - name: Test
        run: npm test
        working-directory: src/
